aruco_pipeline:
  # === Camera Lists ===
  camera_lists: ["one", "two", "three"]
  
  # === Params ===
  num_threads: 4
  marker_length: 0.07
  gui: true
  image_encoding: "bgr8"
  
  # === TF ===
  tf_frame_id:
    parent: "map"
    one: "cam_left_color_optical_frame"
    two: "cam_mid_color_optical_frame"
    three: "cam_right_color_optical_frame"
  
  # === Subscribe Topics ===
  camera_info:
    one: "/vision/cam_left/color/camera_info"
    two: "/vision/cam_mid/color/camera_info"
    three: "/vision/cam_right/color/camera_info"
  
  image_sub:
    one: "/vision/cam_left/color/image_raw"
    two: "/vision/cam_mid/color/image_raw"
    three: "/vision/cam_right/color/image_raw"
  
  # === Publish Topics ===
  image_pub:
    one: "/vision/aruco/sima/left/debug_image"
    two: "/vision/aruco/sima/mid/debug_image"
    three: "/vision/aruco/sima/right/debug_image"
  
  superstar_pose_topic: "/vision/aruco/superstar_pose"
  sima_pose_array_topic: "/vision/aruco/sima_pose_array"

  superstar_id: 14
  sima_group_id: [7, 12, 13]