services:
  realsense:
    image: vision-main:realsense
    container_name: realsense
    volumes:
      - /dev:/dev
      - $LOCAL_WORKSPACE_FOLDER/config/dds-uri/localDDS.xml:/tmp/dds.xml
      - $LOCAL_WORKSPACE_FOLDER/packages/realsense-pkg:/home/realsense/vision-ws/src/realsense-ros
      - $LOCAL_WORKSPACE_FOLDER/packages/camera-pkg:/home/realsense/vision-ws/src/camera-ros
    device_cgroup_rules:
      - "c 81:* rmw"
      - "c 189:* rmw"
    command: >
      bash -ic "
      colcon build --packages-select realsense2_camera camera_ros;
      source /home/realsense/vision-ws/install/local_setup.bash;
      ros2 launch realsense2_camera rs_triple_camera_launch.py & 
      sleep 5 &&
      ros2 launch camera_ros image_stitch.launch.py;
      "
      
  center:
    image: vision-main:center
    container_name: center
    volumes:
      - $LOCAL_WORKSPACE_FOLDER/config/dds-uri/cycloneDDS.xml:/tmp/dds.xml
      - $LOCAL_WORKSPACE_FOLDER/packages/center-pkg:/home/center/vision-ws/src/center-ros
    command: bash