x-common-vars: &common-vars
  tty: true
  stdin_open: true
  ipc: host
  network_mode: host
  stop_grace_period: 1s
  environment:
    RMW_IMPLEMENTATION: rmw_cyclonedds_cpp 
    ROS_DOMAIN_ID: $ROS_DOMAIN_ID
    CYCLONEDDS_URI: /tmp/dds.xml

x-gpu-vars: &gpu-vars
  ipc: host
  shm_size: 8gb
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

services:
  center:
    build:
      context: .
      target: center
      args:
        USER: center
    <<: *common-vars
    profiles: ['center']
    
  realsense:
    build:
      context: .
      target: realsense  
      args:
        USER: realsense
        LIBREALSENSE_VERSION: $LIBREALSENSE_VERSION
        REALSENSE_ROS_VERSION: $REALSENSE_ROS_VERSION
    privileged: true
    <<: *common-vars
    cpuset: "0-9"
    cpus: 8.5
    cpu_shares: 1024
    profiles: ['camera']

  aruco:
    build:
      context: .
      target: aruco 
      args:
        USER: aruco
    <<: *common-vars
    cpuset: "10-15"
    cpus: 5.5
    cpu_shares: 1024
    profiles: ['aruco']

  ultralytics-ros:
    build:
      context: .
      target: ultralytics-ros
      args:
        USER: ultralytics
    <<: 
      - *common-vars
      - *gpu-vars
    profiles: ['yolo']

  ultralytics-training:
    build:
      context: .
      target: ultralytics-ros
    <<: 
      - *common-vars
      - *gpu-vars
    profiles: ['train']
    
  gui:
    build:
      context: .
      target: gui
      args:
        USER: gui
    <<: *common-vars
    # environment:
    #   DISPLAY: $DISPLAY
    profiles: ['gui']
  