x-common-vars: &common-vars
  tty: true
  stdin_open: true
  network_mode: host
  stop_grace_period: 1s
  environment:
    RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
    ROS_DOMAIN_ID: 42

services:
  realsense:
    build:
      context: .
      target: realsense  
      args:
        USER: realsense
        LIBREALSENSE_VERSION: 2.56.2
    <<: *common-vars
    profiles: ['base']

  aruco:
    build:
      context: .
      target: aruco 
      args:
        USER: aruco
    <<: *common-vars
    profiles: ['module']

  pytorch-training:
    build:
      context: .
      target: pytorch-training
    <<: *common-vars
    deploy:
     resources:
       reservations:
         devices:
           - driver: nvidia
             count: 1
             capabilities: [gpu]
    shm_size: 6gb
    profiles: ['train']
    
  gui:
    build:
      context: .
      target: gui
      args:
        USER: gui
    <<: *common-vars
    environment:
      DISPLAY: $DISPLAY
      WAYLAND_DISPLAY: $WAYLAND_DISPLAY
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      ROS_DOMAIN_ID: 42
    profiles: ['gui']
  