# Common environment for services
x-common-env: &common-env
  tty: true
  stdin_open: true
  privileged: true
  stop_grace_period: 1s

# Services
services:
  realsense: 
    build:
      context: .
      target: realsense  
      args:
        USER: realsense
    <<: *common-env
    network_mode: host
    image: vision-main:realsense
    container_name: realsense
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/bus/usb:/dev/bus/usb
      - $PWD/../ws/realsense-pkg:/home/realsense/vision-ws/src/realsense-ros
    environment:
      - DISPLAY=${DISPLAY}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=42
    command: bash -ic "colcon build && bash"
  
  aruco:
    build:
      context: .
      target: aruco 
      args:
        USER: aruco
    <<: *common-env
    network_mode: host
    image: vision-main:aruco
    container_name: aruco
    volumes:
      - $PWD/../ws/aruco-pkg:/home/aruco/vision-ws/src/aruco-ros
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=42
    command: bash

  gui:
    build:
      context: .
      target: gui
      args:
        USER: gui
    <<: *common-env
    network_mode: host
    image: vision-main:gui
    container_name: gui
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=42
    command: bash -ic "rqt"