# Docker
ARCH: jetson # amd64 | arm64 | arm64-igpu | jetson
BASE_IMAGE: ros:humble

# ROS DDS
DDS: cyclone # cyclone | fastdds
ROS_DOMAIN_ID: 14

# Compose
PROJECT_NAME: vision-main
PROFILES: stitcher,yolo # center | camera | aruco | yolo | train | gui | stitch | stitcher

# Build / Run
ACTION: run  # build | run | both
