# Docker
ARCH: amd64 # amd64 | arm64 | arm64-igpu
BASE_IMAGE: ros:humble

# ROS DDS
DDS: cyclone # cyclone | fastdds
ROS_DOMAIN_ID: 11

# Compose
PROJECT_NAME: vision-main
PROFILES: aruco # center | camera | aruco | yolo | train | gui

# Build / Run
ACTION: both # build | run | both
