# Docker
ARCH: arm64-igpu # amd64 | arm64 | arm64-igpu
BASE_IMAGE: ros:humble

# ROS DDS
DDS: cyclone # cyclone | fastdds
ROS_DOMAIN_ID: 11

# Compose
PROJECT_NAME: vision-main
PROFILES: yolo # center | camera | aruco | yolo | train | gui | stitch

# Build / Run
ACTION: run # build | run | both
