aruco_pipeline:
  ros__parameters:
    robot_pose_topic: "/vision/aruco/robot_pose"
    rival_pose_topic: "/vision/aruco/rival_pose"
    num_threads: 3
    marker_length: 0.07
    gui: true
    sync_queue_size: 10
    image_encoding: "bgr8"

    camera_info:
      left: "/vision/cam_left/color/camera_info"
      mid: "/vision/cam_mid/color/camera_info"
      right: "/vision/cam_right/color/camera_info"

    image_pub:
      left: "/vision/aruco/left/image_raw"
      mid: "/vision/aruco/mid/image_raw"
      right: "/vision/aruco/right/image_raw"

    image_sub:
      left: "/vision/cam_left/color/image_raw"
      mid: "/vision/cam_mid/color/image_raw"
      right: "/vision/cam_right/color/image_raw"
