services:
  ros2-cuda:
    build:
      context: .  
      dockerfile: Dockerfile
    image: ros2-cuda:12.4.1-base
    container_name: ros2_cuda_container
    environment:
      - LANG=en_US.UTF-8
      - PYTHONIOENCODING=utf-8
      - ROS_DISTRO=humble
      - ROS_ROOT=/opt/ros/${ROS_DISTRO}
      - ROS_PYTHON_VERSION=3
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: bash  
    stdin_open: true  
    tty: true

