x-common-vars: &common-vars
  tty: true
  stdin_open: true
  ipc: host
  network_mode: host
  stop_grace_period: 1s
  environment:
    RMW_IMPLEMENTATION: rmw_cyclonedds_cpp 
    ROS_DOMAIN_ID: $ROS_DOMAIN_ID
    CYCLONEDDS_URI: /tmp/dds.xml

x-gpu-vars: &gpu-vars
  ipc: host
  shm_size: 8gb
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

services:
  center:
    image: vision-main/center:latest
    container_name: center
    <<: *common-vars
    profiles: ['center']
    
  realsense:
    image: vision-main/realsense:latest
    container_name: realsense
    privileged: true
    <<: *common-vars
    cpuset: "0-9"
    cpus: 8.5
    cpu_shares: 1024
    profiles: ['camera']

  aruco:
    image: vision-main/aruco:latest
    container_name: aruco
    <<: *common-vars
    cpuset: "10-15"
    cpus: 5.5
    cpu_shares: 1024
    profiles: ['aruco']

  ultralytics-ros:
    image: vision-main/ultralytics-ros:latest
    container_name: ultralytics-ros
    <<: 
      - *common-vars
      - *gpu-vars
    profiles: ['yolo']

  ultralytics-training:
    image: ultralytics/ultralytics:latest
    container_name: ultralytics-training
    <<: 
      - *common-vars
      - *gpu-vars
    profiles: ['train']
    
  gui:
    image: vision-main/gui:latest
    container_name: gui
    <<: *common-vars
    profiles: ['gui']
  