services:
  center:
    volumes:
      - $LOCAL_WS/config/dds-uri/cycloneDDS.xml:/tmp/dds.xml
      - $VISION_WS/center-pkg:/home/center/vision-ws/src/center-ros
    command: bash

  realsense:
    volumes:
      - /dev:/dev
      - $LOCAL_WS/config/dds-uri/localDDS.xml:/tmp/dds.xml
      - $VISION_WS/realsense-pkg:/home/realsense/vision-ws/src/realsense-ros
      - $VISION_WS/camera-pkg:/home/realsense/vision-ws/src/camera-ros
    device_cgroup_rules:
      - "c 81:* rmw"
      - "c 189:* rmw"
    command: >
      bash -ic "
      colcon build --packages-select realsense2_camera camera_ros;
      source /home/realsense/vision-ws/install/local_setup.bash;
      ros2 launch realsense2_camera rs_triple_camera_launch.py & 
      sleep 5 &&
      ros2 launch camera_ros image_stitch.launch.py;
      "

  aruco:
    volumes:
      - $LOCAL_WS/config/dds-uri/localDDS.xml:/tmp/dds.xml
      - $VISION_WS/aruco-pkg:/home/aruco/vision-ws/src/aruco-ros
    command: >
      bash -ic "
      colcon build --parallel-workers 6;
      source /home/aruco/vision-ws/install/local_setup.bash;
      ros2 launch aruco_ros CB_ALL.launch.py;
      "
  
  ultralytics-ros:
    volumes:
      - $LOCAL_WS/config/dds-uri/localDDS.xml:/tmp/dds.xml
      - $VISION_WS/ultralytics-pkg:/home/ultralytics/vision-ws/src/ultralytics-ros
    command: >
      bash -ic "
      colcon build;
      source /home/ultralytics/vision-ws/install/local_setup.bash;
      ros2 launch ultralytics_ros yolo_launch.py
      "

  ultralytics-training:
    volumes:
      - $LOCAL_WS/dataset:/root/train
    working_dir: /root/train
    command: bash
      # bash -ic 'nvidia-smi && bash'
  
  gui:
    volumes:
      # X11 socket
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/gui/.Xauthority
      # Wayland socket
      # - $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:/tmp/$WAYLAND_DISPLAY
      # GUI config
      - $LOCAL_WS/config/gui-config:/home/gui/.rviz2
      - $LOCAL_WS/config/dds-uri/localDDS.xml:/tmp/dds.xml
    command: ros2 launch foxglove_bridge foxglove_bridge_launch.xml address:=localhost port:=8765